### ISSUE TITLE
data-sets build isn't automatically triggering

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/data-sets#11]
When a change is made to the data-sets repo the build on wash doesn't automatically run

**Comment by jackjia-ibm** [comment]
@stevenhorsman do we still have this issue? Or it was ephemeral and had gone?

**Comment by stevenhorsman** [comment]
Good question - I think it might be gone, so let's close it, but I'll keep an eye out next time I push a change to master and reopen if necessary
