### ISSUE TITLE
Support Single Sign on SSO data-sets-api

### ISSUE THREAD

**Issue by jordanCain** [zowe/data-sets#133]
The jobs API server should be compatible with the SSO solution provided by the api layer

**Comment by jordanCain** [comment]
Parent Epic: https://github.com/zowe/community/issues/366

**Comment by jordanCain** [comment]
We need to ensure that in the instance when the z/OSMF JWT is not being used api calls can still be authenticated to z/OSMF via an Ltpa token

**Comment by stevenhorsman** [comment]
Is this different from #18?

**Comment by jordanCain** [comment]
Closing as duplicate of #18
