### ISSUE TITLE
USS file api doesn't return the contents of binary file correctly

### ISSUE THREAD

**Issue by std4lqi** [zowe/data-sets#143]
**Describe the bug**
We'd like to get the contents of binary file on USS. According to API doc, we can add "Convert=True" in HTTP request header, which adds "X-IBM-Data-Type=binary" to the request header for z/OSMF, so that we can have the data without being translated with any encoding/decoding.

But we got the binary file contents, in which any char larger than 0x7F is replaced with the three bytes (0xEF, 0xBF, and 0xBD).

**Comment by jordanCain** [comment]
@std4lqi Hi Qi, This issue will be looked into once SSO has been implemented for the data-sets api. We should be able to tackle this issue sometime in March

**Comment by jordanCain** [comment]
@std4lqi Would you be able to provide an example binary file you were seeing this issue with?

**Comment by std4lqi** [comment]
@jordanCain Hi Jordan, we found this problem in getting the contents of SMF dump file. This problem should happen with the regular binary file like pax file. Let me know please, if you need SMF dump file. Thanks!

**Comment by std4lqi** [comment]
@jordanCain Hi Jordan, we found this problem in getting the contents of SMF dump file. This problem should happen with the regular binary file like pax file. Let me know please, if you need SMF dump file. Thanks!

**Comment by NakulManchanda** [comment]
@std4lqi  was able to replicate and found this alternative
https://github.com/zowe/explorer-api-common/pull/45

Verified with `png image binary data` able to decode it back to image after plugin in value of  `response['content']` property.

But it introduces extra step to for you guys to `decode content from b64 to binary` again.
We can introduce `extra header or some http header` to indicate content encoded in b64.
Will that work for you? Thanks!

**Comment by NakulManchanda** [comment]
![image](https://user-images.githubusercontent.com/4791635/76167879-6778e980-6140-11ea-879b-d877fb3c5f78.png)

**Comment by std4lqi** [comment]
@NakulManchanda The result looks good. I'm fine with BASE64 decoding. The "Convert=True" is still required, right? Thanks!

**Comment by NakulManchanda** [comment]
@std4lqi yes, convert=True still required.

**Comment by NakulManchanda** [comment]
Done, and merged with PR #152
