### ISSUE TITLE
Integrate zowe SSO into data-sets-api-server

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/data-sets#18]
#### Acceptance Criteria
*Scenario 1: username API SSO*  
    *Given* I'm a valid zowe user with username <X> and have authenticated to the gateway (eg the catalog)
    *When* I do GET /api/v1/datasets/username
    *Then* I receive the response:
```javascript
{
  "username": "STEVENH"
}
```

*Scenario 2: Data set GET API SSO*  
    *Given* I'm a valid zowe user and have authenticated to the gateway (eg the catalog)
    *When* I do a GET on /api/v1/datasets/<DATA>  
    *Then* I'm not prompted for my logon and get the correct response for my user

#### Implementation details:
Atlas can use /login on API Gateway to get the JWT token (stored in HttpOnly cookie)
The REST endpoints are specified in https://github.com/gizafoundation/api-layer/wiki/Zowe-Authentication-and-Authorization-Service (will be migrated to Zowe GitHub)
Atlas gets the JWT token in a HttpOnly cookie in a header from UI in browser
Atlas is using /query on API Gateway to check the validity of the token
Atlas sends this token to other services in HTTP Header (Authentication Bearer)
Atlas server accesses the z/OSMF via the API Gateway so the gateway can use the LTPA token for z/OSMF

Questions: Do we want to support standalone and zowe SSO?

**Comment by trode05** [comment]
Suggested change in description: 
** Description **
As a user of the Zowe, I would like Data Sets API service to use the Zowe SSO solution for login.

** Acceptance criteria: ** 
Service API is using /login on API Gateway to get the JWT token 
Authentication REST endpoints are specified in https://github.com/zowe/api-layer/wiki/Zowe-Authentication-and-Authorization-Service
Service API is using /query on API Gateway to check the validity of the token
Service API sends this token to other services in HTTP Header (Authentication Bearer)
Service API accesses the z/OSMF via the API Gateway so the gateway can use the LTPA token for z/OSMF
