### ISSUE TITLE
Investigate improving newline handling

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/data-sets#25]
Current from the UI hex control characters eg hex tab and newline cause the apis to reject the request, so it needs converting to \n \t etc.
Investigate if this is required

**Comment by phaumer** [comment]
This is of high-priority for us as every Windows user seems to experience that additional empty lines have been inserted when they bring the file back.

![image](https://user-images.githubusercontent.com/4391934/51689426-83a4e000-1fab-11e9-9aa2-ccb1ec8f67d3.png)

**Comment by stevenhorsman** [comment]
@phaumer - is this using the new 1.0 APIs?

**Comment by phaumer** [comment]
No, 0.9.4, @stevenhorsman

**Comment by mcgrawk** [comment]
@alvin-tan , can this receive a priority?

**Comment by stevenhorsman** [comment]
@mcgrawk - Kelly you really need to verify if the latest version has the same issue

**Comment by jordanCain** [comment]
@phaumer @mcgrawk Can you please validate you're still seeing this behaviour in 1.0.0+ so this can be appropriately prioritised

**Comment by jordanCain** [comment]
@reetchow Thanks for the update, I'm in the process of getting a Windows environment I can replicate this on but in the meantime can you let me know

1. Is this when you get a dataset for the first time or is it after doing an update to the file?
2. Can the same behaviour be observed in the Zowe MVS explorer? (This will help to determine if it's only Theia on Windows or Windows users in general)
