### ISSUE TITLE
Create dataset parameter combination that fails

### ISSUE THREAD

**Issue by Colin-Stone** [zowe/data-sets#37]
Get a 500 response and zosmf is unable to subsequently return datasets for the HLQ if you create a partitioned dataset with a null blocksize. For example:

allocationUnit: TRACK
blockSize: null
dataSetOrganization: PO
directoryBlocks: 10
name: STONECC.TEST.GOOD
primary: 300
recordFormat: FB
recordLength: 80
secondary: 100

Note that if blocksize is removed the post is successful 
(Delete dataset via MVS and zosmf is okay again)

This issue was created using the explorer_mvs ui. https://github.com/zowe/explorer-mvs/issues/50

**Comment by Colin-Stone** [comment]
Got the same issue with this combination too. Although I have stopped nulls being passed, there is still not enough info to satisfy the request
allocationUnit: "TRACK"
blockSize: 80
dataSetOrganization: "PO"
name: "STONECC.TEST.FIX2"
primary: 300
recordFormat: "fb"
secondary: 100

**Comment by stevenhorsman** [comment]
I've spoken to the raiser and can't reproduce
