### ISSUE TITLE
Provide unit tests and examples for conversion of many different code pages that customers use

### ISSUE THREAD

**Issue by phaumer** [zowe/data-sets#40]
I assume we need more parameter for conversions of code pages, line feeds, supporting binaries, etc.
To assume we cover a representative set of conversions unit/integrations tests that cover many examples from different countries and standards would be good so that extension teams can be confident that their client's needs are covered as well as more tests can be contributed by the community.

**Comment by mcgrawk** [comment]
@alvin-tan Can this one get prioritized as well?
