### ISSUE TITLE
HTTP 500 for {datasetName}/content with special characters (#, %, hex < x40)

### ISSUE THREAD

**Issue by MarkAckert** [zowe/data-sets#53]
(Originally from Nakul M on Zowe Slack)

**Describe the bug**
When attempting to access dataset contents with special characters (e.g. #INFO, %OPT), the service returns 500.

```
{"timestamp":"2019-02-20T20:25:23.651+0000","status":500,"error":"Internal Server Error","message":"The request was rejected because the URL contained a potentially malicious String \"%25\"","path":"/api/v1/datasets/ZOWE.JCL(%252303OPT)/content"}
```

**To Reproduce**
1. Browse datasets in Zowe Desktop through MVS Explorer Plugin
2. Click on a dataset with a special character in its name (#, %)
3. See error in log, and no content shown in MVS Explorer

**Expected behavior**
HTTP 200.

**Screenshots**
![image](https://user-images.githubusercontent.com/35308966/53177631-61a87880-35be-11e9-9f90-9410e7b84b5f.png)
![image 1](https://user-images.githubusercontent.com/35308966/53177630-61a87880-35be-11e9-8bb4-6fbc1c03742a.png)

**Comment by MarkAckert** [comment]
Related note from Sean Grady:
```
Be careful that it's even possible for PDS members to contain unprintable characters (below hex 40). So, hopefully percent encoding can be used in a way that translates to EBCDIC properly for those ranges
```

**Comment by NakulManchanda** [comment]
_**ZOWE Dataset API**_   **/api/v1/{dataset}/content**  only this seem to have this restriction it dont support hex url encoding for special symbols like # to %23

it could be because of stricthttpfirewall in spring-security 4-2

_**ZOSMF Dataset API**_ -  **zosmf/restfiles/ds/{dataset}** it works fine - hex url encoding is supported here

**Comment by stevenhorsman** [comment]
Raise by a customer in slack: https://openmainframeproject.slack.com/archives/CBW5ET69G/p1562052805038400

**Comment by 1000TurquoisePogs** [comment]
This should be solvable via uri encode&decode but care must be taken to not disturb any # used for routing, or ? for query. Probably, the solution will look like this one https://github.com/zowe/zlux-app-manager/pull/110/files
