### ISSUE TITLE
Lightweight  dataset list

### ISSUE THREAD

**Issue by lamgibrcom** [zowe/data-sets#58]
*Customer content*

As consumer for the REST-API I'd like to improve the performances of the listing for large dataset list. 

**Describe the solution you'd like**
Added new endpoint for pure dataset list using X-IBM-Attributes=dsname in order to be able to list the datasets also if they are archived and the flag for the "silent recovery" is off . 

**Describe alternatives you've considered**

**Additional context**
Adopted mapper pattern to convert JSON response into internal DTO using MapStruct.

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by stevenhorsman** [comment]
I think this item is complete now
