### ISSUE TITLE
Try it out option for unix get file content endpoint fails due to auto encoding /

### ISSUE THREAD

**Issue by jordanCain** [zowe/data-sets#60]
**Describe the bug**
When selecting the try it out option for the unix get file content endpoint within the Swagger UI the request will fail for any provided path. 

**To Reproduce**
1. Go to Swagger UI
2. Click on Unix files get content endpoint
3. Enter a valid path to a file '/u/jcain/file.txt'
4. Execute and see request auto encodes the path parameter slashes '/'

**Expected behavior**
The Swagger UI should not change the request path parameter

**Additional context**
There is a limitation with the Swagger UI see - https://github.com/swagger-api/swagger-ui/issues/1637

**Comment by std4lqi** [comment]
The "/api/v1/unixfiles/{path}/**" in Swagger UI  is a little misleading. I finally find it should be "/api/v1/unixfiles/u/jcain/file.txt", without "**". One example would be helpful nearby the message of "Try it out function will not work ..."
