### ISSUE TITLE
USS Write APIs

### ISSUE THREAD

**Issue by phaumer** [zowe/data-sets#75]
*Customer content*

**Is your feature request related to a problem? Please describe.**
Need to be able to write content back via REST APIs and have option to convert content to the target (UTF or EBCDIC).
Need to be able to delete content on host
Need to be able to change file meta-data such as tags and permissions
Need to be able to move and copy files on the host.

**Describe the solution you'd like**
Extended set of REST apis with parameters

**Describe alternatives you've considered**
SSH, but not fit for a REST API replacement

**Additional context**

---
*Engineering team info (eg https://github.com/zowe/explorer-jes/issues/4)*

**As a** [type of user],  
**I want** [some goal]  
**so that** [some reason].

*Details/notes*  
[Detail - implementation notes]

#### Acceptance Criteria

**Scenario 1:* [Title]  
*Given* [context]  
   *And* [some more context]...  
*When* [event]  
*Then* [outcome]  
    *And* [another outcome]...

**Comment by jordanCain** [comment]
I'm closing this issue as I have raised the following four items to track independently 
USS Update file contents endpoint #83
USS Create file/directory endpoint #84
USS Delete file/directory endpoint #85
USS Update file/directory meta-data #86
