### ISSUE TITLE
USS GET directory listing which user in not authorised returns 500 RC instead of 403

### ISSUE THREAD

**Issue by lauren-li** [zowe/data-sets#77]
**Describe the bug**
In the Zowe 0.9.4 API, a 403 (Forbidden) error was returned if the user requested to view contents a USS folder they did not have permission to view. In Zowe 1.0.1, the new API returns a 500 error.

**To Reproduce**
1. Go to the Swagger UI for Zowe 1.0.1 (e.g. https://tvt4119.svl.ibm.com:8547/swagger-ui.html#/).
2. Expand 'Unix Files APIs'.
3. Expand 'GET /api/v1/unixfiles' and click "Try it out".
4. In the input field for `path`, enter the path to a folder your user does not have permission to (e.g. `/u/zoweph` or `/u/zowebjs`).
5. See a 500 error returned.

**Expected behavior**
When the user requests to view contents of a USS folder they do not have permission to, return a 403 (Forbidden) error.

**Screenshots**
Screenshot of 500 error:
<img width="1174" alt="Screen Shot 2019-03-18 at 11 38 15 AM" src="https://user-images.githubusercontent.com/45975633/54543331-dc717300-4973-11e9-88be-19a52a2c4058.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: All
 - Version [e.g. 22]: N/A

**Additional context**

**Comment by jordanCain** [comment]
This should be fixed by https://github.com/zowe/data-sets/pull/66
